
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwertyuiop123.



uploadFile:
  # 配置文件上传的存储路径
  path: D:\E\ideaProject\project\src\main\resources\static\
  # 上传的文件的访问ip，为空则默认项目运行环境的ip
  port:
  # 上传的文件的访问端口，为空则默认项目运行环境的端口
  ip:
  # 上传的文件的访问前置url
  beforeUrl: /


#日志文件输出位置
logging:
 path: /root/project/logs/
 file: info.log